#!/bin/bash

# Check if battery exists
if [ ! -f /sys/class/power_supply/BAT0/capacity ]; then
  exit
fi

# Check battery status (charging or not)
if [ "$(cat /sys/class/power_supply/BAT0/status)" == "Charging" ]; then
  BAT="$(cat /sys/class/power_supply/BAT0/capacity)"
  echo " ${BAT}󱐋"
else
  BAT="$(cat /sys/class/power_supply/BAT0/capacity)"
  for x in ${BAT}; do
    case $x in
    100 | 9[0-9])
      echo "  "
      ;;
    70[0-9] | 6[0-9] | [5-9][0-9])
      echo "  "
      ;;
    50[0-9] | 4[0-9] | [3-9][0-9])
      echo "  "
      ;;
    30[0-9] | 2[0-9] | 1[0-9] | [1-9])
      echo "  "
      ;;
    *)
      echo "  "
      ;;
    esac
  done
fi
